name 'puppet-jenkins'
version '0.1.0'
source 'git://github.com/jbouse/puppet-jenkins.git'
author 'ugns'
description 'Jenkins CI platform'
summary 'Jenkins CI platform'
license 'UNLICENSED'
project_page 'https://github.com/jbouse/puppet-jenkins'

dependency 'puppetlabs/apt', '>=1.1.0 <2.0.0'
